name: Run docker
on: push

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      PAT: ${{secrets.PAT}}
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v2
      - name: compose
        run: |
          docker build -t pat --build-arg PAT=$PAT .
          docker run pat

